version: "3.7"
services:

  gateway:
    image: vapormap-gateway
    ports:
      - 8080:80
    environment:
      - FRONTEND_URL=frontend
      - FRONTEND_PORT=8000
      - BACKEND_URL=backend
      - BACKEND_PORT=8001
      - SERVER_PORT=80
      - SERVER_ADDRESS=localhost

  frontend:
    image: vapormap-dev-fe-wb
    environment:
      - VAPORMAP_BACKEND=localhost
      - VAPORMAP_BACKEND_PORT=8080
    volumes:
      - type: bind
        source: ../frontend
        target: /app

  backend:
    image: vapormap-dev-be-wb
    volumes:
      - type: bind
        source: ../app
        target: /app



