# Generated by Django 2.2.1 on 2019-05-29 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190524_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(90.0), django.core.validators.MinValueValidator(-90.0)]),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(180.0), django.core.validators.MinValueValidator(-180.0)]),
        ),
    ]
